// <auto-generated />
namespace AdminPanelDevice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class lastdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(lastdb));
        
        string IMigrationMetadata.Id
        {
            get { return "201801091342590_last db "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
